empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListaAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shorname>/', views.ListaByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('listar-by-trabajo/<jobempleado>/', views.ListaByTrabajo.as_view()),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.persona.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/persona/models.py
from django.db import models
#
from applications.departamento.models import Departamento

from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 

# Create your models here.
class Empleado(models.Model):
    
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    #contador
    #administrador
    #economista
    #otro
    fisrt_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('nombres completos', max_length=50, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True) 
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()
    #image = models.ImageField(, upload_to=None, height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering=['fisrt_name', 'last_name']
        unique_together = ('fisrt_name', 'departamento') 
    
    def __str__(self):
        return str(self.id) + '-' + self.fisrt_name + '-' + self.last_name

empleado/applications/persona/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'fisrt_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

empleado/applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
) 
# models
from .models import Empleado
# forms
from .forms import EmpleadoForm

class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'inicio.html'


class ListaAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'fisrt_name'
    context_object_name = 'empleados'
    #model = Empleado
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'fisrt_name'
    context_object_name = 'empleados'
    model = Empleado
    
    
class ListaByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__name=area
        )
        return lista


class ListaByTrabajo(ListView):
    template_name = 'persona/list_by_trabajo.html'

    def get_queryset(self):
        trabajo = self.kwargs['jobempleado']
        lista2 = Empleado.objects.filter(
            job=trabajo
        )
        return lista2


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('******************')
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            fisrt_name=palabra_clave
        )
        
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=8)
        return empleado.habilidades.all()



class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name = "persona/success.html"



class EmpleadoCreateView(CreateView):
    template_name = 'persona/add.html'
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.fisrt_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form) 


class EmpleadoUpdateView(UpdateView):
    template_name = 'persona/update.html'
    model = Empleado 
    fields = ['fisrt_name', 'last_name', 'job', 'departamento', 'habilidades']
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('***************METODO POST*************')
        print('=======================================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        
        print('***********METODO form valid***********')
        print('***************************************')
        return super(EmpleadoUpdateView, self).form_valid(form) 



class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')


        
    #queryset = Empleado.objects.filter(
        #departamento__name='area de contabilidad'
    #)
    #tarea al final listar empleados por trabajo.

    #como controlar lo que llevamos y hacemos para sustentar el costo.
    
    

empleado/templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar Empleado
{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1>registrar empleado</h1>
            <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

                <div class="medium-6 cell">
                    <label>Nombres:
                      {{form.fisrt_name}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos:
                      {{form.last_name}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo:
                      {{form.job}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento::
                      {{form.departamento}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Habilidades:
                      {{form.habilidades}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Foto:
                      {{form.avatar}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="button success">Guardar</button>
                </div>
    
            </form>
        </div>
    </div>
{% endblock content %}
    

empleado/templates/persona/by_kword.html
<h1>buscar empleado por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>


<h3>lista de resultados</h3>

<ul>
    
    {% for e in empleados  %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.full_name }}</h1>

        <form class="cell" method="POST">{% csrf_token %}

            <div class="callout secondary">
                <h5>Desea elimina este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>

        </form>

    </div>

</div>

{% endblock content %}
    
    

empleado/templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{object.full_name}}
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px">
            <div class="card-divider">
              {{empleado.get_job_display}}
            </div>
            {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
            {% else %}
            <img src="{% static 'img/standard.jpg' %}">
            {% endif %}
            <div class="card-section">
              <h4>{{ empleado.full_name }}</h4>
              <p>{{ empleado.last_name }}</p>
              <p>{{ empleado.departamento.shor_name }}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                  
                  {% for h in empleado.habilidades.all %}
                      <li>{{ h.habilidad }}</li>
                  {% endfor %}
                      
              </ul>
              
            </div>
        </div>

    </div>

</div>
    
{% endblock content %}
    
    
<h1>detalle de un empleado {{ titulo }}</h1>
{{ empleado }}

<h3>Todos los datos:</h3>
<p>{{ empleado.fisrt_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>
<p>{{ empleado.habilidades }}</p>

empleado/templates/persona/habilidades.html
<h1>Habilidades de empleado</h1>

<ul>
    
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

empleado/templates/persona/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                      <td>{{ e.id }}</td>
                      <td>{{ e.fisrt_name }}</td>
                      <td>{{ e.last_name }}</td>
                      <td>{{ e.departamento }}</td>
                      <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                    {% endif %}
                        
                    
                    {% for pagina in paginator.page_range %}
                    
                    {% ifequal pagina page_obj.number  %} 
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>    
                    
                    {% endifequal %}
                    {% endfor %}
                        

                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                    {% endif %}
                </ul>
            </nav>
                
            {% endif %}
        </div>
    </div>
    
 
</div>

{% endblock content %}
    

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista empleados po departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por departamento:</div>
              <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                          <td>{{ e.id }}</td>
                          <td>{{ e.fisrt_name }}</td>
                          <td>{{ e.last_name }}</td>
                          <td>{{ e.departamento }}</td>
                          <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                 
              </div>


        </div>

    </div>
{% endblock content %}
    
    
<h1>lista empleados por departamento</h1>

<ul>

{% for e in object_list %}
    <li>{{ e }}</li>
{% endfor %}

</ul>
    

empleado/templates/persona/list_by_trabajo.html
<h1>lista de empleados por trabajo</h1>

<ul>
    
{% for e in object_list %}
    <li>{{ e }}</li>
{% endfor %}
        
</ul>

empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                      <td>{{ e.id }}</td>
                      <td>{{ e.fisrt_name }}</td>
                      <td>{{ e.last_name }}</td>
                      <td>{{ e.departamento }}</td>
                      <td><a class="button succes" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a></td>
                      <td><a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                    {% endif %}
                        
                    
                    {% for pagina in paginator.page_range %}
                    
                    {% ifequal pagina page_obj.number  %} 
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>    
                    
                    {% endifequal %}
                    {% endfor %}
                        

                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</a></li>
                    {% endif %}
                </ul>
            </nav>
                
            {% endif %}
        </div>
    </div>
    
 
</div>

{% endblock content %}
    

empleado/templates/persona/success.html
<h1>felicitaciones, se guardo corectamente el empleado!! </h1>

empleado/templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Edtar Empleado
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}
  
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                      {{form.fisrt_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                      {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo::
                      {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                      {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades Extra:
                      {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    
    