empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views
	
app_name = "departamento_app"

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListaAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shorname>/', views.ListaByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('listar-by-trabajo/<jobempleado>/', views.ListaByTrabajo.as_view()),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('',include('applications.departamento.urls')),
    re_path('',include('applications.home.urls')),
    re_path('',include('applications.persona.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, editable=True)
    shor_name = models.CharField('Nombre corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering=['-name']
        unique_together = ('name', 'shor_name')
    

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

        

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20) 

empleado/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView

from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm



class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'



class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('*****estamos en el form valid*****')

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            fisrt_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

empleado/templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.name %}">Ver Empleados</a>
                            </td>
                        </tr> 
                        {% endfor %}
                            
                        
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock content %}
    
    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    registrar departamento
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                  {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{form.apellidos}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                  {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Shorname:
                  {{form.shorname}}
                </label>
            </div>
            <div class="medium 12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>

        </form>
    </div>
</div>    
{% endblock content %}
    
    
<h1>registrar nuevo departamento</h1>

<form method="POST">{% csrf_token %}
    <h3>Datos empleado:</h3>
    <p>
        {{form.nombre}}
    </p>
    <p>
        {{form.apellidos}}
    </p>
    <h3>Datos departamento:</h3>
    <p>
        {{form.departamento}}
    </p>
    <p>
        {{form.shorname}}
    </p>

    <button type="submit">Guardar</button>

</form>